[workspace]
resolver = "2"
members = [
  "crates/reticulum",
  "crates/reticulum-daemon",
]

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/BeechatNetworkSystemsLtd/Reticulum-rs"
